[NYU]
source   = imaps+oauthbearer://po524%40nyu.edu@imap.gmail.com?token_endpoint=https://oauth2.googleapis.com/token&client_id=406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com&client_secret=kSmqreRr0qwBWJgbf5Y-PjSU
source-cred-cmd = gpg --batch --quiet --decrypt ~/.config/aerc/nyu-refresh-token.gpg
outgoing   = smtps+oauthbearer://po524%40nyu.edu@smtp.gmail.com:465?token_endpoint=https://oauth2.googleapis.com/token&client_id=406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com&client_secret=kSmqreRr0qwBWJgbf5Y-PjSU
outgoing-cred-cmd = gpg --batch --quiet --decrypt ~/.config/aerc/nyu-refresh-token.gpg
from     = Panos Oikonomou <po524@nyu.edu>
cache-headers = true
